### ISSUE TITLE
[FEATURE]: end-to-end tests

### ISSUE THREAD

**Issue by shanduur** [linode/linode-cosi-driver#52]
### Are you interested in contributing to the development of this feature?

Yes

### Is your feature request related to a problem? Please describe.

Our current testing process lacks comprehensive coverage, particularly in terms of end-to-end testing. This leads to potential issues going unnoticed until later stages of development or even in production.

### Describe the solution you'd like.

I would like to implement end-to-end tests to ensure that all components of our application work together as expected. These tests should simulate real user scenarios, covering the entire application workflow from start to finish.

### Describe alternatives you've considered.

One alternative is to rely solely on unit tests and integration tests. However, these tests may not capture all possible interactions between components and may miss issues that arise only in the context of the entire application workflow.

### Additional Information

End-to-end tests will not only improve the quality of our software but also increase confidence in our releases by catching potential issues earlier in the development process. Additionally, they can serve as living documentation of our application's behavior and help onboard new team members more effectively.

**Comment by mhmxs** [comment]
There are a few popular test frameworks on the market:
https://github.com/vapor-ware/kubetest - Python based
https://github.com/kubeshop/testkube - Only for testing, supports multiple test tools
https://github.com/tilt-dev/tilt - Mostly a developer tool
https://github.com/kyverno/chainsaw - Only for testing, stand-alone tool, popular at Linode
https://garden.io/ - Supports both dev env and test execution, supports multiple test tools
